#!bin/bash
# Shell agnostic stuff that should be run for every new shell instance and
# not only the login shell like in ~/.profile file case.

# Source ~/.profile if it hasn't been done yet
if [ -z $PROFILE_SOURCED ]; then
    . ${HOME}/.profile
fi

### Misc
    # Enable color support of ls and also add handy aliases
    if [ -x /usr/bin/dircolors ]; then
        test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
        alias ls='ls --color=auto'
        #alias dir='dir --color=auto'
        #alias vdir='vdir --color=auto'

        alias grep='grep --color=auto' \
            fgrep='fgrep --color=auto' \
            egrep='egrep --color=auto'
    fi

    # Some more ls aliases
    alias ll='ls -alF' \
        la='ls -A' \
        l='ls -CF'

    # Add an "alert" alias for long running commands. Use like so:
    #   sleep 10; alert
    alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

    alias ka="killall" \
        e="$EDITOR" \
        sdn="pkill --full '/opt/brave.com/brave/brave --disable-lcd-text' && shutdown now" \
        rbtn="pkill --full '/opt/brave.com/brave/brave --disable-lcd-text' && shutdown -r now" \
        ls="ls -hN --color=auto --group-directories-first" \
        grep="grep --color=auto" \
        diff="diff --color=auto" \
        cp="cp -iv"

    # Open a file with editor
    se() { du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf | xargs -r "$EDITOR" ;}

    alias less="less -i"

    # Print signals and corresponding values easily (not all shells show signals' corresponding values)
    alias signals-show="bash -c 'kill -l'"

    # Use echo to print to stderr
    echoerr() { echo "$@" 1>2; }

    # Don't print default startup message on running GNU R
    alias R="R --quiet"

### Movement
    alias gc="cd ~/.config" \
        gD="cd ~/Documents" \
        gd="cd ~/Downloads" \
        gP="cd ~/Media/Pictures/Wallpapers" \
        gp="cd ~/Projects" \
        gV="cd ~/Media/Videos" \
        gv="cd ~/Void" \
        gs="cd ~/.scripts" \
        gS="cd ~/Studia" \
        g.="cd ~/dotfiles" \
        gn="cd ~/Notes" \
        gl="cd ~/.local" \
        gt="cd $XDG_DATA_HOME/Trash" \
        gb="cd -"

### Systemd
    alias sctl="systemctl"
    alias sctlu="systemctl --user"

### GDB
alias gdbt=gdb-tmux

### Shell specifics
if [[ $SHELL == /usr/bin/zsh ]]; then
    eval "$(pyenv init - zsh)"
elif [[ $SHELL == /usr/bin/bash ]]; then
    eval "$(pyenv init - bash)"
fi
