#!bin/bash

### Misc
    # Enable color support of ls and also add handy aliases
    if [ -x /usr/bin/dircolors ]; then
        test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
        alias ls='ls --color=auto'
        #alias dir='dir --color=auto'
        #alias vdir='vdir --color=auto'

        alias grep='grep --color=auto' \
            fgrep='fgrep --color=auto' \
            egrep='egrep --color=auto'
    fi

    # Some more ls aliases
    alias ll='ls -alF' \
        la='ls -A' \
        l='ls -CF'

    # Add an "alert" alias for long running commands. Use like so:
    #   sleep 10; alert
    alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

    alias ka="killall" \
        e="$EDITOR" \
        sdn="pkill --full '/opt/brave.com/brave/brave --disable-lcd-text' && shutdown now" \
        rbtn="pkill --full '/opt/brave.com/brave/brave --disable-lcd-text' && shutdown -r now" \
        ls="ls -hN --color=auto --group-directories-first" \
        grep="grep --color=auto" \
        diff="diff --color=auto" \
        cp="cp -iv"

    # Open a file with editor
    se() { du -a ~/.scripts/* ~/.config/* | awk '{print $2}' | fzf | xargs -r "$EDITOR" ;}

    alias less="less -i"

### Movement
    alias gc="cd ~/.config" \
        gD="cd ~/Documents" \
        gd="cd ~/Downloads" \
        gP="cd ~/Media/Pictures/Wallpapers" \
        gp="cd ~/Projects" \
        gV="cd ~/Media/Videos" \
        gv="cd ~/Void" \
        gs="cd ~/.scripts" \
        g.="cd ~/dotfiles" \
        gn="cd ~/Notes" \
        gl="cd ~/.local" \
        gt="cd ~/.trash" \
        gb="cd -"

### Git
    alias git?="clear -x; git status; git log --oneline -5" \
        gits="git status --short" \
        gitd="git diff --output-indicator-new='+' --output-indicator-old='-'" \
        gitds="git diff --staged --output-indicator-new='+' --output-indicator-old='-'" \
        gitap="git add --patch" \
        gitc="git commit" \
        gitps="git push" \
        gitpl="git pull" \
        gitl="git log --oneline" \
        gitl="git log --all --graph --pretty=format:'%C(magenta)%h %C(white) %an  %ar%C(auto)  %D%n%s%n'" \
        gitb="git branch" \
        giti="git init" \
        gitcl="git clone"


### Systemd
    alias sctl="systemctl"
    alias sctl="systemctl --user"